### PR TITLE
fix: proper conversion of Uint8List

### PR DESCRIPTION
**Pull request by samtuga1**

### CODE REVIEW

**Comment by rrousselGit** [comment]
I see I'm using an SDK that's up-to-date: https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#dartconvert

I'll fix this by bumping the minimum Dart SDK instead.

**Comment by rrousselGit** [comment]
Thanks for the fix though!

**Comment by samtuga1** [comment]
> I don't see why your changes should change anything. `utf8.encode` returns a `Uint8List` for me, not `List<int>`.
> 
> Out of curiosity, which Dart version are you using?

I am using Dart SDK version: 3.1.0 (stable)

**Comment by samtuga1** [comment]
> I see I'm using an SDK that's up-to-date: https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#dartconvert
> 
> I'll fix this by bumping the minimum Dart SDK instead.

That will certainly work as well 👍🏽

**Pull request closed without merging**
