### PR TITLE
Fix #21: Pass localId to user update request

### LINKED ISSUE #21: Updating user data based on UID fails
I have issue updating the user data based on user's bid. First, I retrieve the user's data by email, and I get what I expect. Then, I used the uid from the response for updating the user's data, but I keep getting the following error:

```
E/flutter (13587): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FirebaseAuthAdminException: auth/missinguid: A uid identifier is required for the current operation.
E/flutter (13587): #0      validateResponse (package:_discoveryapis_commons/src/api_requester.dart:306:9)
E/flutter (13587): <asynchronous suspension>
E/flutter (13587): #1      ApiRequester.request (package:_discoveryapis_commons/src/api_requester.dart:72:16)
E/flutter (13587): <asynchronous suspension>
E/flutter (13587): #2      AccountsResource.update (package:firebaseapis/identitytoolkit/v1.dart:714:23)
E/flutter (13587): <asynchronous suspension>
E/flutter (13587): #3      _AuthHttpClient.setAccountInfo.<anonymous closure> (package:dart_firebase_admin/src/auth/auth_api_request.dart:966:24)
E/flutter (13587): <asynchronous suspension>
E/flutter (13587): #4      _AbstractAuthRequestHandler.updateExistingAccount (package:dart_firebase_admin/src/auth/auth_api_request.dart:733:22)
E/flutter (13587): <asynchronous suspension>
E/flutter (13587): #5      _BaseAuth.updateUser (package:dart_firebase_admin/src/auth/base_auth.dart:772:9)
E/flutter (13587): <asynchronous suspension>
E/flutter (13587): #6      LoginController.login.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:stock_log/app/modules/login/controllers/login_controller.dart:162:23)
E/flutter (13587): <asynchronous suspension>
E/flutter (13587): #7      LoginController.login.<anonymous closure>.<anonymous closure> (package:stock_log/app/modules/login/controllers/login_controller.dart:149:13)
E/flutter (13587): <asynchronous suspension>
E/flutter (13587): #8      LoginController.login.<anonymous closure> (package:stock_log/app/modules/login/controllers/login_controller.dart:144:11)
E/flutter (13587): <asynchronous suspension>
E/flutter (13587): #9      LoginController.login (package:stock_log/app/modules/login/controllers/login_controller.dart:87:28)
E/flutter (13587): <asynchronous suspension>
E/flutter (13587): 
``` 

Here is my code:

```dart
await auth.getUserByEmail(email.value).then((user) async {
            String uid = user.uid;
            await auth
                .updateUser(uid, ath.UpdateRequest(password: code.toString()))
                .then((value) async {
              print('USER UPDATED');
              print(value.toJson());
            });
          });
```

### PR DESCRIPTION
**Pull request by HeySreelal**
Fixes #21.

This might a be missed implementation, when sending `GoogleCloudIdentitytoolkitV1SetAccountInfoRequest` localId (which is basically the UID) was not set to the passed UID. Hence caused #21.

Tested locally, please let me know if we are looking to add tests somehow for this.

Cheers!

### CODE REVIEW

**Comment by rrousselGit** [comment]
Hello! Sorry for the delay

Could you add a test for this?

**Comment by HeySreelal** [comment]
Hey @rrousselGit, no problem! I'll quickly add a test for this one.

**Comment by HeySreelal** [comment]
Hi again @rrousselGit, can you please check if the added test case is enough for this? Regards :)

**Comment by rrousselGit** [comment]
LGTM, thanks!

**Pull request merged**
